version: '3.8'

services:
  trafficctrl:
    image: trafficctrl:v0.1.0
    container_name: trafficctrl
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - TARGET_URL=http://localhost:5000
      - PROXY_PORT=8080
      - METRICS_PORT=8090
      - DRY_RUN_MODE=false
      - REDIS_ADDRESS=localhost:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_USE_TLS=false
      - LOG_LEVEL=info
      - LOG_ENVIRONMENT=development
    network_mode: host